# Generated by Django 4.2.13 on 2024-07-06 20:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text')),
                ('photo', models.ImageField(blank=True, upload_to=posts.models.location_image_upload)),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when post was added', verbose_name='Created At')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='Date and time when post was updated', null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'starnavi_posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when post was added', verbose_name='Created At')),
                ('dt_updated', models.DateTimeField(auto_now=True, help_text='Date and time when post was updated', null=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'starnavi_comments',
            },
        ),
    ]
