# Generated by Django 4.2.13 on 2024-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Is Blocked'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Is Blocked'),
        ),
    ]
