# Generated by Django 4.2.13 on 2024-07-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_is_blocked_post_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='enable_auto_reply',
            field=models.BooleanField(default=False, verbose_name='Enable Auto Reply'),
        ),
    ]
