version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .envs/.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_ninja_test
      - POSTGRES_PASSWORD=django_ninja_test
      - POSTGRES_DB=django_ninja_test_db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
